### ISSUE TITLE
Vite Fails to Resolve Entry for Package "muigui"

### ISSUE THREAD

**Issue by townboy123** [greggman/muigui#2]
## Problem Description
When using Vite to build my project, I encountered the following error:
[vite] Internal server error: Failed to resolve entry for package "muigui". The package may have incorrect main/module/exports specified in its package.json.

## Environment Information
- Operating System: Windows 10
- Vite Version: vite@5.2.9
- Node.js Version: v20.12.2
- muigui Version: muigui@0.0.16

## Steps to Reproduce
1. Initialize the project:
npm i muigui

2.Relevant Code Snippet
`import GUI from 'muigui';

/**
 * this is test code.
 */
const start = () => {
	const gui = new GUI();
};

start();`

## Additional Information
I suspect that the issue might be due to incorrect configuration of the main or module fields in muigui's package.json.
If you need further information, please let me know.
Thank you for your help!

## Temporary fix
![ff487205f3a34abaed862f9ac028cd23](https://github.com/user-attachments/assets/409bee86-a633-4839-906c-242d3c4d3ada)

**Comment by snowfrogdev** [comment]
Yep, I run into this as well.
